export const InvoiceColumns = [
    { text: 'Invoice', datafield: 'invoice', width: 120 },
    { text: 'Date', datafield: 'date', width: 120 },
    { text: 'Customer', datafield: 'customer', width: 120 },
    { text: 'Key', datafield: 'key', width: 120 },
    { text: 'Goods', datafield: 'goods', width: 120 },
    { text: 'GoodsVat', datafield: 'goodsVat', width: 120 },
    { text: 'Discount', datafield: 'discount', width: 120 },
    { text: 'DiscVat', datafield: 'discVat', width: 120 },
    { text: 'Subtotal', datafield: 'subtotal', width: 120 },
    { text: 'SubtotalVat', datafield: 'subtotalVat', width: 120 },
    { text: 'Delivery', datafield: 'delivery', width: 120 },
    { text: 'DeliveryVat', datafield: 'deliveryVat', width: 120 },
    { text: 'Packing', datafield: 'packing', width: 120 },
    { text: 'PackingVat', datafield: 'packingVat', width: 120 },
    { text: 'Total', datafield: 'total', width: 120 },
    { text: 'TotalVat', datafield: 'totalVat', width: 120 },
    { text: 'InvoiceTotal', datafield: 'invoiceTotal', width: 120 },
    { text: 'Vated', datafield: 'vated', width: 120 },
    { text: 'Country', datafield: 'country', width: 120 },
    { text: 'Delivery Addr1', datafield: 'deliveryAddr1', width: 120 },
    { text: 'Delivery Addr2', datafield: 'deliveryAddr2', width: 120 },
    { text: 'Delivery Addr3', datafield: 'deliveryAddr3', width: 120 },
    { text: 'Delivery Addr4', datafield: 'deliveryAddr4', width: 120 },
    { text: 'Delivery Addr5', datafield: 'deliveryAddr5', width: 120 },
    { text: 'Credit Charge', datafield: 'creditCharge', width: 120 },
    { text: 'Cust Ref', datafield: 'custRef', width: 120 },
    { text: 'Currency', datafield: 'currency', width: 120 },
    { text: 'Edited', datafield: 'edited', width: 120 },
    { text: 'Edited By', datafield: 'editedBy', width: 120 },
    { text: 'Sales Person', datafield: 'salesPerson', width: 120 },
    { text: 'Created', datafield: 'created', width: 120 },
    { text: 'CreatedBy', datafield: 'createdBy', width: 120 },
    { text: 'Print Count', datafield: 'printCount', width: 120 },
    { text: 'Fax Count', datafield: 'faxCount', width: 120 },
    { text: 'Email Count', datafield: 'emailCount', width: 120 },
    { text: 'Delivery Address', datafield: 'deliveryAddr', width: 120 },
    { text: 'Advice Note No', datafield: 'adviceNoteNo', width: 120 },
    { text: 'Haulier', datafield: 'haulier', width: 120 },
    { text: 'Posted', datafield: 'posted', width: 120 },
    { text: 'Carrier Code', datafield: 'carrierCode', width: 120 },
    { text: 'Carrier Weight', datafield: 'carrierWeight', width: 120 },
    { text: 'Carrier Parcels', datafield: 'carrierParcels', width: 120 },
    { text: 'Carrier Shipped', datafield: 'carrierShipped', width: 120 },
    { text: 'Web Order No', datafield: 'webOrderNo', width: 120 },
    { text: 'IP Addr', datafield: 'ipAddr', width: 120 },
    { text: 'Import No', datafield: 'importNo', width: 120 },
    { text: 'Site', datafield: 'site', width: 120 },
    { text: 'Trolleys', datafield: 'trolleys', width: 120 },
    { text: 'Weight', datafield: 'weight', width: 120 },
    { text: 'Despatch Points', datafield: 'despatchPoint', width: 120 },
    { text: 'Handheld Id', datafield: 'handheldId', width: 120 },
    { text: 'Parent Order', datafield: 'parentOrder', width: 120 },
    { text: 'Child No', datafield: 'childNo', width: 120 },
    { text: 'Load No', datafield: 'loadNo', width: 120 },
    { text: 'Pay Status', datafield: 'payStatus', width: 120 },
    { text: 'Pay Method', datafield: 'payMethod', width: 120 },
    { text: 'Comment', datafield: 'comment', width: 120 },
    { text: 'Full Comment', datafield: 'fullComment', width: 120 },

]
export const InvoiceDetailColumns = [
    { text: 'Invoice', datafield: 'invoice', width: 120 },
    { text: 'Name', datafield: 'name', width: 120 },
    { text: 'Size', datafield: 'size', width: 120 },
    { text: 'Form', datafield: 'form', width: 120 },
    { text: 'Sold', datafield: 'sold', width: 120 },
    { text: 'Price', datafield: 'price', width: 120 },
    { text: 'Discount', datafield: 'discount', width: 120 },
    { text: 'Total', datafield: 'total', width: 120 },
    { text: 'Vat', datafield: 'vat', width: 120 },
    { text: 'Order', datafield: 'order', width: 120 },
    { text: 'Location', datafield: 'location', width: 120 },
    { text: 'Batch', datafield: 'batch', width: 120 },
    { text: 'User Batch', datafield: 'userBatch', width: 120 },
    { text: 'Initial Cost', datafield: 'initialCost', width: 120 },
    { text: 'Del.Note', datafield: 'delNote', width: 120 },
    { text: 'Pick List', datafield: 'pickList', width: 120 },
    { text: 'Passport', datafield: 'passport', width: 120 },
    { text: 'Certificate', datafield: 'certificate', width: 120 },
    { text: 'Retail', datafield: 'retail', width: 120 },
    { text: 'Own', datafield: 'own', width: 120 },
    { text: 'Category', datafield: 'category', width: 120 },
    { text: 'Sec.Size', datafield: 'secSize', width: 120 },
    { text: 'Sec.Form', datafield: 'secForm', width: 120 },
    { text: 'Key', datafield: 'key', width: 120 },
    { text: 'Line', datafield: 'line', width: 120 },
    { text: 'Tx Price', datafield: 'txPrice', width: 120 },
    { text: 'Tx Vat', datafield: 'txVat', width: 120 },
    { text: 'Tx Total', datafield: 'txTotal', width: 120 },
    { text: 'Tx Retail', datafield: 'txRetail', width: 120 },
    { text: 'EAN8', datafield: 'ean8', width: 120 },
    { text: 'EAN13', datafield: 'ean13', width: 120 },
    { text: 'EPOS', datafield: 'epos', width: 120 },
    { text: 'Sub True', datafield: 'subTrue', width: 120 },
    { text: 'Sub Name', datafield: 'subName', width: 120 },
    { text: 'Sub Size', datafield: 'subSize', width: 120 },
    { text: 'Sub Form', datafield: 'subForm', width: 120 },
    { text: 'Per Tray', datafield: 'perTray', width: 120 },
    { text: 'Trays', datafield: 'trays', width: 120 },
    { text: 'Product ID', datafield: 'productId', width: 120 },
    { text: 'Van Sale Order', datafield: 'vanSaleOrder', width: 120 },
    { text: 'Van Sale Line', datafield: 'vanSaleLine', width: 120 },
    { text: 'Parent', datafield: 'parent', width: 120 },
    { text: 'Child', datafield: 'child', width: 120 },
    { text: 'Parent Key', datafield: 'parentKey', width: 120 },
    { text: 'Parent Line', datafield: 'parentLine', width: 120 },
    { text: 'Parent Order', datafield: 'parentOrder', width: 120 },
    { text: 'Parent Order Line', datafield: 'parentOrderLine', width: 120 },
    { text: 'Child No', datafield: 'childNo', width: 120 },
    { text: 'Date', datafield: 'date', width: 120 },
    { text: 'Current Cost', datafield: 'currentCost', width: 120 },
    { text: 'Despatched', datafield: 'despatched', width: 120 },

]
export const PurchaseInvoieColumns = [
    { text: 'Invoice', datafield: 'invoice', width: 120 },
    { text: 'Date', datafield: 'date', width: 120 },
    { text: 'Order', datafield: 'order', width: 120 },
    { text: 'Supplier', datafield: 'supplier', width: 120 },
    { text: 'Key', datafield: 'key', width: 120 },
    { text: 'Del Note', datafield: 'delNote', width: 120 },
    { text: 'Goods', datafield: 'goods', width: 120 },
    { text: 'Goods Vat', datafield: 'goodsVat', width: 120 },
    { text: 'Discount', datafield: 'discount', width: 120 },
    { text: 'Disc Vat', datafield: 'discVat', width: 120 },
    { text: 'Subtotal', datafield: 'subtotal', width: 120 },
    { text: 'Subtotal Vat', datafield: 'subtotalVat', width: 120 },
    { text: 'Delivery', datafield: 'delivery', width: 120 },
    { text: 'Delivery Vat', datafield: 'deliveryVat', width: 120 },
    { text: 'Packing', datafield: 'packing', width: 120 },
    { text: 'Paking Vat', datafield: 'pakingVat', width: 120 },
    { text: 'Total', datafield: 'total', width: 120 },
    { text: 'Total Vat', datafield: 'totalVat', width: 120 },
    { text: 'Inv Total inc Vat', datafield: 'invTotalIncVat', width: 120 },
    { text: 'Country', datafield: 'country', width: 120 },
    { text: 'CompanyName', datafield: 'companyName', width: 120 },
    { text: 'Delivery Address1', datafield: 'deliveryAddress1', width: 120 },
    { text: 'Delivery Address2', datafield: 'deliveryAddress2', width: 120 },
    { text: 'Delivery Address3', datafield: 'deliveryAddress3', width: 120 },
    { text: 'Delivery Address4', datafield: 'deliveryAddress4', width: 120 },
    { text: 'Delivery Address5', datafield: 'deliveryAddress5', width: 120 },
    { text: 'Last Updated', datafield: 'lastUpdated', width: 120 },
    { text: 'Updated By', datafield: 'updatedBy', width: 120 },
    { text: 'Created', datafield: 'created', width: 120 },
    { text: 'Created By', datafield: 'createdBy', width: 120 },
    { text: 'Print Count', datafield: 'printCount', width: 120 },
    { text: 'Fax Count', datafield: 'faxCount', width: 120 },
    { text: 'Email Count', datafield: 'emailCount', width: 120 },
    { text: 'Posted', datafield: 'posted', width: 120 },
    { text: 'Nursery Suite', datafield: 'nurserySuite', width: 120 },
    { text: 'Items', datafield: 'items', width: 120 },
    { text: 'Line Items', datafield: 'lineItems', width: 120 },
    { text: 'Supplier Invoice No', datafield: 'supplierInvoiceNo', width: 120 },
    { text: 'Comment', datafield: 'comment', width: 120 },
    { text: 'Full Comment', datafield: 'fullComment', width: 120 },
]
export const PurchaseInvoieDetailColumns = [
    { text: 'GRN No', datafield: 'grnNo', width: 120 },
    { text: 'Invoice', datafield: 'invoice', width: 120 },
    { text: 'Key', datafield: 'key', width: 120 },
    { text: 'Name', datafield: 'name', width: 120 },
    { text: 'Size', datafield: 'size', width: 120 },
    { text: 'Form', datafield: 'form', width: 120 },
    { text: 'Del', datafield: 'del', width: 120 },
    { text: 'Price', datafield: 'price', width: 120 },
    { text: 'Discount', datafield: 'discount', width: 120 },
    { text: 'Total', datafield: 'total', width: 120 },
    { text: 'Vat', datafield: 'vat', width: 120 },
    { text: 'Vat Rate', datafield: 'vatRate', width: 120 },
    { text: 'Vat Code', datafield: 'vatCode', width: 120 },
    { text: 'Supplier Del No', datafield: 'supplierDelNo', width: 120 },
    { text: 'Category', datafield: 'category', width: 120 },
    { text: 'Order', datafield: 'order', width: 120 },
    { text: 'Supplier', datafield: 'supplier', width: 120 },
    { text: 'Sup.Passport', datafield: 'supPassport', width: 120 },
    { text: 'Sup.Cert.No', datafield: 'supCertNo', width: 120 },
    { text: 'Comment', datafield: 'comment', width: 120 },
    { text: 'Line No', datafield: 'lineNo', width: 120 },
    { text: 'Tx Price', datafield: 'txPrice', width: 120 },
    { text: 'Tx Total', datafield: 'txTotal', width: 120 },
    { text: 'Sec.Size', datafield: 'secSize', width: 120 },
    { text: 'Sec.Form', datafield: 'secForm', width: 120 },
    { text: 'Ean8', datafield: 'ean8', width: 120 },
    { text: 'Ean13', datafield: 'ean13', width: 120 },
    { text: 'Epos', datafield: 'epos', width: 120 },
]