export const OrderColumns = [
    { text: 'Order', datafield: 'order', width: 120 },
    { text: 'Date', datafield: 'date', width: 120 },
    { text: 'Supplier', datafield: 'supplier', width: 120 },
    { text: 'Key', datafield: 'key', width: 120 },
    { text: 'Required', datafield: 'required', width: 120 },
    { text: 'Items', datafield: 'items', width: 120 },
    { text: 'Value', datafield: 'value', width: 120 },
    { text: 'Plants', datafield: 'plants', width: 120 },
    { text: 'Staus', datafield: 'status', width: 120 },
    { text: 'Last Delivery', datafield: 'lastDelivery', width: 120 },
    { text: 'Vated', datafield: 'vated', width: 120 },
    { text: 'Currency', datafield: 'currency', width: 120 },
    { text: 'Last Edit', datafield: 'lastEdit', width: 120 },
    { text: 'Operator', datafield: 'operator', width: 120 },
    { text: 'Supp.Ref', datafield: 'supplyRef', width: 120 },
    { text: 'PrintCount', datafield: 'printCount', width: 120 },
    { text: 'FaxCount', datafield: 'faxCount', width: 120 },
    { text: 'EmailCount', datafield: 'emailCount', width: 120 },
    { text: 'Site', datafield: 'site', width: 120 },
    { text: 'Booked In Date', datafield: 'bookedInDate', width: 120 },
    { text: 'Created', datafield: 'created', width: 120 },
    { text: 'Crated By', datafield: 'createdBy', width: 120 },
    { text: 'Delivery Type', datafield: 'deliveryType', width: 120 },
    { text: 'Comment', datafield: 'comment', width: 120 },
    { text: 'Full Comment', datafield: 'fullComment', width: 120 },

];
export const OrderDetailColums = [
    { text: 'Order', datafield: 'order', width: 120 },
    { text: 'Name', datafield: 'name', width: 120 },
    { text: 'Size', datafield: 'size', width: 120 },
    { text: 'Form', datafield: 'form', width: 120 },
    { text: 'Ordered', datafield: 'ordered', width: 120 },
    { text: 'Delivered', datafield: 'delivered', width: 120 },
    { text: 'Outstanding', datafield: 'outstanding', width: 120 },
    { text: 'Allocated', datafield: 'allocated', width: 120 },
    { text: 'CalledUp', datafield: 'calledup', width: 120 },
    { text: 'Price', datafield: 'price', width: 120 },
    { text: 'Sub-Total', datafield: 'subTotal', width: 120 },
    { text: 'Vat', datafield: 'vat', width: 120 },
    { text: 'Total', datafield: 'total', width: 120 },
    { text: 'Discount', datafield: 'discount', width: 120 },
    { text: 'Required', datafield: 'required', width: 120 },
    { text: 'Comment', datafield: 'comment', width: 120 },
    { text: 'Category', datafield: 'category', width: 120 },
    { text: 'Vat Rate', datafield: 'vatRate', width: 120 },
    { text: 'Sec.Size', datafield: 'secSize', width: 120 },
    { text: 'Sec.Form', datafield: 'secForm', width: 120 },
    { text: 'Key', datafield: 'key', width: 120 },
    { text: 'Line', datafield: 'line', width: 120 },
    { text: 'Tx Price', datafield: 'txPrice', width: 120 },
    { text: 'Tx Sub-Total', datafield: 'txSubTotal', width: 120 },
    { text: 'Per Tray', datafield: 'perTray', width: 120 },
    { text: 'Trays', datafield: 'trays', width: 120 },
    { text: 'Batch Price', datafield: 'batchPrice', width: 120 },
    { text: 'Tx Batch Price', datafield: 'txBatchPrice', width: 120 },
    { text: 'Vat Code', datafield: 'vatCode', width: 120 },
    { text: 'Booked In Date', datafield: 'bookedInDate', width: 120 },
    { text: 'Product Id', datafield: 'productId', width: 120 },
    { text: 'Ean8', datafield: 'ean8', width: 120 },
    { text: 'Ean13', datafield: 'ean13', width: 120 },
    { text: 'Epos', datafield: 'epos', width: 120 },
    { text: 'Date', datafield: 'date', width: 120 },
];
export const GoodsReceivedNoteColumns = [
    { text: 'Grn No', datafield: 'grnNo', width: 120 },
    { text: 'Order', datafield: 'order', width: 120 },
    { text: 'Supplier', datafield: 'supplier', width: 120 },
    { text: 'Sup Del Note', datafield: 'supDelNote', width: 120 },
    { text: 'Date', datafield: 'date', width: 120 },
    { text: 'Grn Value', datafield: 'grnValue', width: 120 },
    { text: 'Tot Ord Qty', datafield: 'totOrdQty', width: 120 },
    { text: 'No Del Items', datafield: 'noDelItems', width: 120 },
    { text: 'Tot Qty Del', datafield: 'totQtyDel', width: 120 },
    { text: 'Tot Qos', datafield: 'totQos', width: 120 },
    { text: 'Currency', datafield: 'currency', width: 120 },
    { text: 'Key', datafield: 'key', width: 120 },
    { text: 'Print Count', datafield: 'printCount', width: 120 },
    { text: 'Fax Count', datafield: 'faxCount', width: 120 },
    { text: 'Email Count', datafield: 'emailCount', width: 120 },
    { text: 'Site', datafield: 'site', width: 120 },
    { text: 'Created', datafield: 'created', width: 120 },
    { text: 'Created By', datafield: 'createdBy', width: 120 },
    { text: 'Call Up No', datafield: 'callupNo', width: 120 },
    { text: 'Comment', datafield: 'comment', width: 120 },
    { text: 'Full Comment', datafield: 'fullComment', width: 120 },
];
export const GoodsReceivedNoteDetailColumns = [
    { text: 'Pono', datafield: 'pono', width: 120 },
    { text: 'Item', datafield: 'item', width: 120 },
    { text: 'Size', datafield: 'size', width: 120 },
    { text: 'Form', datafield: 'form', width: 120 },
    { text: 'Sec.Size', datafield: 'secSize', width: 120 },
    { text: 'Sec.Form', datafield: 'secForm', width: 120 },
    { text: 'Key', datafield: 'key', width: 120 },
    { text: 'Date Req', datafield: 'dateReq', width: 120 },
    { text: 'Tx Price', datafield: 'TxPrice', width: 120 },
    { text: 'Category', datafield: 'category', width: 120 },
    { text: 'Tot Value', datafield: 'totValue', width: 120 },
    { text: 'Discount', datafield: 'discount', width: 120 },
    { text: 'Vat', datafield: 'vat', width: 120 },
    { text: 'Qty Delivered', datafield: 'qtyDelivered', width: 120 },
    { text: 'Comment', datafield: 'comment', width: 120 },
    { text: 'Batch', datafield: 'batch', width: 120 },
    { text: 'Userbatch', datafield: 'userBatch', width: 120 },
    { text: 'Price', datafield: 'price', width: 120 },
    { text: 'Growing', datafield: 'growing', width: 120 },
    { text: 'Saleable', datafield: 'saleable', width: 120 },
    { text: 'Rejected', datafield: 'rejected', width: 120 },
    { text: 'Batch Price', datafield: 'batchPrice', width: 120 },
    { text: 'Tx Batch Price', datafield: 'txBatchPrice', width: 120 },
    { text: 'VAT Code', datafield: 'vatCode', width: 120 },
    { text: 'Site', datafield: 'site', width: 120 },
    { text: 'Location', datafield: 'location', width: 120 },
    { text: 'Tx Tot Value', datafield: 'txTotValue', width: 120 },
    { text: 'Call Up No', datafield: 'callupNo', width: 120 },
    { text: 'PO Line No', datafield: 'polineNo', width: 120 },
    { text: 'Ean8', datafield: 'ean8', width: 120 },
    { text: 'Ean13', datafield: 'ean13', width: 120 },
    { text: 'Epos', datafield: 'epos', width: 120 },
]