export const OrderColumns = [
    { text: 'Order', datafield: '', width: 120 },
    { text: 'Date', datafield: '', width: 120 },
    { text: 'Supplier', datafield: '', width: 120 },
    { text: 'Key', datafield: '', width: 120 },
    { text: 'Required', datafield: '', width: 120 },
    { text: 'Items', datafield: '', width: 120 },
    { text: 'Value', datafield: '', width: 120 },
    { text: 'Plants', datafield: '', width: 120 },
    { text: 'Staus', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    { text: '', datafield: '', width: 120 },
    
]