export const OrderColumns = [
    { text: 'Order', datafield: 'order', width: 120 },
    { text: 'Date', datafield: 'date', width: 120 },
    { text: 'Customer', datafield: 'customer', width: 120 },
    { text: 'Key', datafield: 'key', width: 120 },
    { text: 'Items', datafield: 'items', width: 120 },
    { text: 'Value', datafield: 'value', width: 120 },
    { text: 'Status', datafield: 'status', width: 120 },
    { text: 'Cust Ref', datafield: 'custRef', width: 120 },
    { text: 'Required', datafield: 'required', width: 120 },
    { text: 'Last Edit', datafield: 'lastEdit', width: 120 },
    { text: 'Edited By', datafield: 'editedBy', width: 120 },
    { text: 'Vat', datafield: 'vat', width: 120 },
    { text: 'Currency', datafield: 'currency', width: 120 },
    { text: 'Delivery Addr1', datafield: 'deliveryAddr1', width: 120 },
    { text: 'Delivery Addr2', datafield: 'deliveryAddr2', width: 120 },
    { text: 'Delivery Addr3', datafield: 'deliveryAddr3', width: 120 },
    { text: 'Delivery Addr4', datafield: 'deliveryAddr4', width: 120 },
    { text: 'Delivery Addr5', datafield: 'deliveryAddr5', width: 120 },
    { text: 'Picklist', datafield: 'packlist', width: 120 },
    { text: 'Delivery Note', datafield: 'deliveryNote', width: 120 },
    { text: 'Backorders', datafield: 'backorder', width: 120 },
    { text: 'Currency', datafield: 'currencyP', width: 120 },
    { text: 'Haulier', datafield: 'haulier', width: 120 },
    { text: 'TextDate', datafield: 'textDate', width: 120 },
    { text: 'Sales Person', datafield: 'salesPerson', width: 120 },
    { text: 'Created', datafield: 'created', width: 120 },
    { text: 'Created By', datafield: 'createdBy', width: 120 },
    { text: 'Print Count', datafield: 'printCount', width: 120 },
    { text: 'Fax Count', datafield: 'faxCount', width: 120 },
    { text: 'Email Count', datafield: 'emailCount', width: 120 },
    { text: 'Delivery Address', datafield: 'deliveryAddr', width: 120 },
    { text: 'Web order No', datafield: 'webOrderNo', width: 120 },
    { text: 'IP Addr', datafield: 'ipAddr', width: 120 },
    { text: 'Import No', datafield: 'importNo', width: 120 },
    { text: 'Site', datafield: 'site', width: 120 },
    { text: 'Booking in Status', datafield: 'bookingStatus', width: 120 },
    { text: 'Booked in Date', datafield: 'bookedDate', width: 120 },
    { text: 'Trolleys', datafield: 'trolleys', width: 120 },
    { text: 'Weight', datafield: 'weight', width: 120 },
    { text: 'Despatch Points', datafield: 'despatchPoint', width: 120 },
    { text: 'STN`s', datafield: 'STN', width: 120 },
    { text: 'Comment', datafield: 'comment', width: 120 },
    { text: 'Booking In Comment', datafield: 'bookingInComment', width: 120 },
    { text: 'HandheldId', datafield: 'handheldId', width: 120 },
    { text: 'ParentOrder', datafield: 'parentOrder', width: 120 },
    { text: 'ChildNo', datafield: 'childNo', width: 120 },
    { text: 'LastChildNo', datafield: 'lastChildNo', width: 120 },
    { text: 'Load No', datafield: 'loadNo', width: 120 },
    { text: 'Load & Go', datafield: 'loadAndGo', width: 120 },
    { text: 'Pay Status', datafield: 'payStatus', width: 120 },
    { text: 'Pay Method', datafield: 'payMethod', width: 120 },
    { text: 'Full Comment', datafield: 'fullComment', width: 120 },
];
export const OrderDetailColums = [
    { text: 'Order', datafield: 'order', width: 120 },
    { text: 'Line', datafield: 'line', width: 120 },
    { text: 'Key', datafield: 'key', width: 120 },
    { text: 'Lname', datafield: 'lname', width: 120 },
    { text: 'Size', datafield: 'size', width: 120 },
    { text: 'Form', datafield: 'form', width: 120 },
    { text: 'Qty', datafield: 'qty', width: 120 },
    { text: 'Del', datafield: 'del', width: 120 },
    { text: 'Qos', datafield: 'qos', width: 120 },
    { text: 'Pick', datafield: 'pick', width: 120 },
    { text: 'Allocated', datafield: 'allocated', width: 120 },
    { text: 'Price', datafield: 'price', width: 120 },
    { text: 'Sub-Total', datafield: 'subTotal', width: 120 },
    { text: 'Rate', datafield: 'rate', width: 120 },
    { text: 'Vat', datafield: 'vat', width: 120 },
    { text: 'Total', datafield: 'total', width: 120 },
    { text: 'Discount', datafield: 'discount', width: 120 },
    { text: 'Required', datafield: 'required', width: 120 },
    { text: 'Comment', datafield: 'comment', width: 120 },
    { text: 'Catname', datafield: 'catname', width: 120 },
    { text: 'Retail Price', datafield: 'retailPrice', width: 120 },
    { text: 'Ean8', datafield: 'ean8', width: 120 },
    { text: 'Ean13', datafield: 'ean13', width: 120 },
    { text: 'Epos', datafield: 'epos', width: 120 },
    { text: 'Sec. Size', datafield: 'secSize', width: 120 },
    { text: 'Sec. Form', datafield: 'secForm', width: 120 },
    { text: 'Tx Price', datafield: 'txPrice', width: 120 },
    { text: 'Tx Sub-Total', datafield: 'txSubTotal', width: 120 },
    { text: 'Sub True', datafield: 'subTrue', width: 120 },
    { text: 'Sub Name', datafield: 'subName', width: 120 },
    { text: 'Sub Size', datafield: 'subSize', width: 120 },
    { text: 'Sub Form', datafield: 'subForm', width: 120 },
    { text: 'Per Tray', datafield: 'perTray', width: 120 },
    { text: 'Trays OS', datafield: 'traysOS', width: 120 },
    { text: 'Van Sale Del', datafield: 'vanSaleDel', width: 120 },
    { text: 'Qty Adj Date', datafield: 'qtyAdjDate', width: 120 },
    { text: 'Qty Adj User', datafield: 'qtyAdjUser', width: 120 },
    { text: 'Qty Adj Admount', datafield: 'qtyAdjAmount', width: 120 },
    { text: 'Qty Adj Reason', datafield: 'qtyAdjReason', width: 120 },
    { text: 'Parent', datafield: 'parent', width: 120 },
    { text: 'Child', datafield: 'child', width: 120 },
    { text: 'Parent Key', datafield: 'parentKey', width: 120 },
    { text: 'Parent Line', datafield: 'parentLine', width: 120 },
    { text: 'Adj Date Req', datafield: 'adjDateReq', width: 120 },
    { text: 'Booking In Status', datafield: 'bookingInStatus', width: 120 },
    { text: 'Parent Order', datafield: 'parentOrder', width: 120 },
    { text: 'Parent Order Line', datafield: 'parentOrderLine', width: 120 },
    { text: 'Child No', datafield: 'childNo', width: 120 },
    { text: 'Date', datafield: 'date', width: 120 },

];
export const CustomerColumns = [
    { text: 'Key', datafield: 'key', width: 120 },
    { text: 'Company Name', datafield: 'companyName', width: 120 },
    { text: 'Contact1', datafield: 'contact1', width: 120 },
    { text: 'Address1', datafield: 'addr1', width: 120 },
    { text: 'Address2', datafield: 'addr2', width: 120 },
    { text: 'Address3', datafield: 'addr3', width: 120 },
    { text: 'Address4', datafield: 'addr4', width: 120 },
    { text: 'Postcode', datafield: 'postcode', width: 120 },
    { text: 'Phone1', datafield: 'phone1', width: 120 },
    { text: 'Phone2', datafield: 'phone2', width: 120 },
    { text: 'Fax1', datafield: 'fax1', width: 120 },
    { text: 'Fax2', datafield: 'fax2', width: 120 },
    { text: 'Mobile1', datafield: 'mobile1', width: 120 },
    { text: 'Mobile2', datafield: 'mobile2', width: 120 },
    { text: 'Contact2', datafield: 'contact2', width: 120 },
    { text: 'Type', datafield: 'type', width: 120 },
    { text: 'Region', datafield: 'region', width: 120 },
    { text: 'Source', datafield: 'source', width: 120 },
    { text: 'Discount', datafield: 'discount', width: 120 },
    { text: 'Email', datafield: 'email', width: 120 },
    { text: 'Select', datafield: 'select', width: 120 },
    { text: 'MailSort', datafield: 'mailSort', width: 120 },
    { text: 'CreditLimit', datafield: 'creditLimit', width: 120 },
    { text: 'CreditStop', datafield: 'creditStop', width: 120 },
    { text: 'Notes', datafield: 'notes', width: 120 },
    { text: 'LastSale', datafield: 'lastSale', width: 120 },
    { text: 'LastInvoice', datafield: 'lastInvoice', width: 120 },
    { text: 'CustSince', datafield: 'custSince', width: 120 },
    { text: 'LastContact', datafield: 'lastContact', width: 120 },
    { text: 'Analysis Code0', datafield: 'aCode0', width: 120 },
    { text: 'Analysis Code1', datafield: 'aCode1', width: 120 },
    { text: 'Analysis Code2', datafield: 'aCode2', width: 120 },
    { text: 'Analysis Code3', datafield: 'aCode3', width: 120 },
    { text: 'Analysis Code4', datafield: 'aCode4', width: 120 },
    { text: 'Analysis Code5', datafield: 'aCode5', width: 120 },
    { text: 'Analysis Code6', datafield: 'aCode6', width: 120 },
    { text: 'Analysis Code7', datafield: 'aCode7', width: 120 },
    { text: 'Analysis Code8', datafield: 'aCode8', width: 120 },
    { text: 'Analysis Code9', datafield: 'aCode9', width: 120 },
    { text: 'Analysis Code10', datafield: 'aCode10', width: 120 },
    { text: 'Analysis Code11', datafield: 'aCode11', width: 120 },
    { text: 'Analysis Code12', datafield: 'aCode12', width: 120 },
    { text: 'Analysis Code13', datafield: 'aCode13', width: 120 },
    { text: 'Analysis Code14', datafield: 'aCode14', width: 120 },
    { text: 'Analysis Code15', datafield: 'aCode15', width: 120 },
    { text: 'Analysis Code16', datafield: 'aCode16', width: 120 },
    { text: 'Analysis Code17', datafield: 'aCode17', width: 120 },
    { text: 'Analysis Code18', datafield: 'aCode18', width: 120 },
    { text: 'Analysis Code19', datafield: 'aCode19', width: 120 },
    { text: 'Invoices', datafield: 'invoices', width: 120 },
    { text: 'Invoiced', datafield: 'invoiced', width: 120 },
    { text: 'Credits', datafield: 'credits', width: 120 },
    { text: 'Credited', datafield: 'credited', width: 120 },
    { text: 'Card 1 No', datafield: 'card1No', width: 120 },
    { text: 'Card 2 No', datafield: 'card2No', width: 120 },
];
export const PicklistColumns = [
    { text: 'Pick List', datafield: 'pickList', width: 120 },
    { text: 'Order', datafield: 'order', width: 120 },
    { text: 'Pick Date', datafield: 'pickDate', width: 120 },
    { text: 'Customer', datafield: 'customer', width: 120 },
    { text: 'Key', datafield: 'key', width: 120 },
    { text: 'Delivery Address1', datafield: 'deliveryAddress1', width: 120 },
    { text: 'Delivery Address2', datafield: 'deliveryAddress2', width: 120 },
    { text: 'Delivery Address3', datafield: 'deliveryAddress3', width: 120 },
    { text: 'Delivery Address4', datafield: 'deliveryAddress4', width: 120 },
    { text: 'Delivery Address5', datafield: 'deliveryAddress5', width: 120 },
    { text: 'Cust Ref', datafield: 'custRef', width: 120 },
    { text: 'Weight', datafield: 'weight', width: 120 },
    { text: 'Unitstock', datafield: 'unitstock', width: 120 },
    { text: 'Currency', datafield: 'currency', width: 120 },
    { text: 'Edited', datafield: 'edited', width: 120 },
    { text: 'Edited By', datafield: 'editedBy', width: 120 },
    { text: 'Sales Person', datafield: 'salesPerson', width: 120 },
    { text: 'Created', datafield: 'created', width: 120 },
    { text: 'Created By', datafield: 'createdBy', width: 120 },
    { text: 'Print Count', datafield: 'printCount', width: 120 },
    { text: 'Fax Count', datafield: 'faxCount', width: 120 },
    { text: 'Email Count', datafield: 'emailCount', width: 120 },
    { text: 'Delivery Address Name', datafield: 'DeliveryAddressName', width: 120 },
    { text: 'Site', datafield: 'site', width: 120 },
    { text: 'Trolleys', datafield: 'trolleys', width: 120 },
    { text: 'Weight', datafield: 'weight', width: 120 },
    { text: 'Dispatch Points', datafield: 'dispatchPoints', width: 120 },
    { text: 'Parent Order', datafield: 'parentOrder', width: 120 },
    { text: 'Child No.', datafield: 'childNo', width: 120 },
    { text: 'Comment', datafield: 'comment', width: 120 },
    { text: 'Full Comment', datafield: 'fullComment', width: 120 },
    { text: 'Line Items', datafield: 'lineItems', width: 120 },
    { text: 'Picklist Items', datafield: 'picklistItems', width: 120 },
]
export const PicklistDetailColumns = [
    { text: 'PickList', datafield: 'pickList', width: 120 },
    { text: 'Order No.', datafield: 'orderNo', width: 120 },
    { text: 'Name', datafield: 'name', width: 120 },
    { text: 'Size', datafield: 'size', width: 120 },
    { text: 'Form', datafield: 'form', width: 120 },
    { text: 'Picked', datafield: 'picked', width: 120 },
    { text: 'Location', datafield: 'location', width: 120 },
    { text: 'Batch', datafield: 'batch', width: 120 },
    { text: 'User Batch', datafield: 'userBatch', width: 120 },
    { text: 'Ean8', datafield: 'ean8', width: 120 },
    { text: 'Ean13', datafield: 'ean13', width: 120 },
    { text: 'Epos', datafield: 'epos', width: 120 },
    { text: 'Retail Price', datafield: 'retailPrice', width: 120 },
    { text: 'Sec. Size', datafield: '', width: 120 },
    { text: 'Sec. Form', datafield: 'secForm', width: 120 },
    { text: 'Nursery', datafield: 'nursery', width: 120 },
    { text: 'Key', datafield: 'key', width: 120 },
    { text: 'Line', datafield: 'line', width: 120 },
    { text: 'Picked Growing', datafield: 'pickedGrowing', width: 120 },
    { text: 'Sub True', datafield: 'subTrue', width: 120 },
    { text: 'Sub Name', datafield: 'subName', width: 120 },
    { text: 'Sub Size', datafield: 'subSize', width: 120 },
    { text: 'Sub Form', datafield: 'subForm', width: 120 },
    { text: 'Per Tray', datafield: 'perTray', width: 120 },
    { text: 'Trays', datafield: 'trays', width: 120 },
    { text: 'Grow Trays', datafield: 'growTrays', width: 120 },
    { text: 'Product ID', datafield: 'productId', width: 120 },
    { text: 'Tx Retail Price', datafield: 'txRetailPrice', width: 120 },
    { text: 'Tx Price', datafield: 'txPrice', width: 120 },
    { text: 'Parent', datafield: 'parent', width: 120 },
    { text: 'Child', datafield: 'child', width: 120 },
    { text: 'Parent Key', datafield: 'parentKey', width: 120 },
    { text: 'Parent Line', datafield: 'parentLine', width: 120 },
    { text: 'Parent Order', datafield: 'parentOrder', width: 120 },
    { text: 'Parent Order Line', datafield: 'parentOrderLine', width: 120 },
    { text: 'Child No.', datafield: 'childNo', width: 120 },
    { text: 'Date', datafield: 'date', width: 120 },
    { text: 'Picklist Name', datafield: 'picklistName', width: 120 },
]