export const InventoryColumns = [
    { text: 'Key', datafield: 'key', width: 120},
    { text: 'Name', datafield: 'name', width: 120},
    { text: 'Size', datafield: 'size', width: 120},
    { text: 'Form', datafield: 'form', width: 120},
    { text: 'Start', datafield: 'start', width: 120},
    { text: 'Stock', datafield: 'stock', width: 120},
    { text: 'Order', datafield: 'order', width: 120},
    { text: 'To Come', datafield: 'toCome', width: 120},
    { text: 'Free', datafield: 'free', width: 120},
    { text: 'Alloc', datafield: 'alloc', width: 120},
    { text: 'Growing', datafield: 'growing', width: 120},
    { text: 'Sold', datafield: 'sold', width: 120},
    { text: 'Lost', datafield: 'lost', width: 120},
    { text: 'Warn', datafield: 'warn', width: 120},
    { text: 'Warn%', datafield: 'warnP', width: 120},
    { text: 'Alloc.Grow', datafield: 'allocGrow', width: 120},
    { text: 'Category', datafield: 'category', width: 120},
    { text: 'Sec.Size', datafield: 'secSize', width: 120},
    { text: 'Sec.Form', datafield: 'secForm', width: 120},
    { text: 'Price A1', datafield: 'priceA1', width: 120},
    { text: 'Price A2', datafield: 'priceA2', width: 120},
    { text: 'Price A3', datafield: 'priceA3', width: 120},
    { text: 'Price A4', datafield: 'priceA4', width: 120},
    { text: 'Price B1', datafield: 'priceB1', width: 120},
    { text: 'Price B2', datafield: 'priceB2', width: 120},
    { text: 'Price B3', datafield: 'priceB3', width: 120},
    { text: 'Price B4', datafield: 'priceB4', width: 120},
    { text: 'Passported', datafield: 'passported', width: 120},
    { text: 'EAN13', datafield: 'ean13', width: 120},
    { text: 'Name', datafield: 'nameP', width: 120},
    { text: 'Size', datafield: 'sizeP', width: 120},
    { text: 'Form', datafield: 'formP', width: 120},
    { text: 'Unused', datafield: 'unused', width: 120},
    { text: 'FreeInc.Grow', datafield: 'freeIncGrow', width: 120},
    { text: 'Unalloc', datafield: 'unalloc', width: 120},
    { text: 'Unalloc.Grow', datafield: 'unallocGrow', width: 120},
    { text: 'RetailA', datafield: 'retailA', width: 120},
    { text: 'RetailB', datafield: 'retailB', width: 120},
    { text: 'Price A', datafield: 'priceA', width: 120},
    { text: 'Price B', datafield: 'priceB', width: 120},
    { text: 'Price A5', datafield: 'priceA5', width: 120},
    { text: 'Price A6', datafield: 'priceA6', width: 120},
    { text: 'Price A7', datafield: 'priceA7', width: 120},
    { text: 'Price A8', datafield: 'priceA8', width: 120},
    { text: 'Price B5', datafield: 'priceB5', width: 120},
    { text: 'Price B6', datafield: 'priceB6', width: 120},
    { text: 'Price B7', datafield: 'priceB7', width: 120},
    { text: 'Price B8', datafield: 'priceB8', width: 120},
    { text: 'Stock Inc.Grow', datafield: 'stockIncGrow', width: 120},
    { text: 'Picture File', datafield: 'file', width: 120},
    { text: 'Per Tray', datafield: 'perTray', width: 120},
    { text: 'Item ID', datafield: 'itemId', width: 120},
    { text: 'Free Exc.Purch', datafield: 'freeExc', width: 120},
    { text: 'Target Sales Value', datafield: 'targetSalesValue', width: 120},
    { text: 'Target Sales Quantity', datafield: 'targetSalesQuantity', width: 120},
    { text: 'Label Botanical Name', datafield: 'botanicalName', width: 120},
    { text: 'Label Common Name', datafield: 'commonName', width: 120},
    { text: 'On Transfer', datafield: 'onTransfer', width: 120},
    { text: 'Despatch Points', datafield: 'despatchPoints', width: 120},
    { text: 'Analysis Code 0', datafield: 'aCode0', width: 120},
    { text: 'Analysis Code 1', datafield: 'aCode1', width: 120},
    { text: 'Analysis Code 2', datafield: 'aCode2', width: 120},
    { text: 'Analysis Code 3', datafield: 'aCode3', width: 120},
    { text: 'Analysis Code 4', datafield: 'aCode4', width: 120},
    { text: 'Analysis Code 5', datafield: 'aCode5', width: 120},
    { text: 'Analysis Code 6', datafield: 'aCode6', width: 120},
    { text: 'Analysis Code 7', datafield: 'aCode7', width: 120},
    { text: 'Pur.EAN13', datafield: 'purEan13', width: 120},
    { text: 'Pur.PriceA1', datafield: 'purPriceA1', width: 120},
    { text: 'Pur.PriceA2', datafield: 'purPriceA2', width: 120},
    { text: 'Pur.PriceA3', datafield: 'purPriceA3', width: 120},
    { text: 'Pur.PriceA4', datafield: 'purPriceA4', width: 120},
    { text: 'Pur.PriceB1', datafield: 'purPriceB1', width: 120},
    { text: 'Pur.PriceB2', datafield: 'purPriceB2', width: 120},
    { text: 'Pur.PriceB3', datafield: 'purPriceB3', width: 120},
    { text: 'Pur.PriceB4', datafield: 'purPriceB4', width: 120},
    { text: 'Royalty', datafield: 'royalty', width: 120},
    { text: 'Royalty Year On', datafield: 'royaltyYear', width: 120},


];
export const NameColumns = [
    { text: 'Key', datafield: 'key', width: 120},
    { text: 'Name', datafield: 'name', width: 120},
    { text: 'Category', datafield: 'category', width: 120},
    { text: 'Passport', datafield: 'passport', width: 120},
    { text: 'Label Line1', datafield: 'label1', width: 120},
    { text: 'Label Line2', datafield: 'label2', width: 120},
    { text: 'Label Line3', datafield: 'label3', width: 120},
    { text: 'Label Line4', datafield: 'label4', width: 120},
    { text: 'Last Update', datafield: 'lastUpdate', width: 120},
    { text: 'User', datafield: 'user', width: 120},
    { text: 'Vat Code', datafield: 'vatCode', width: 120},
    { text: 'Vat Rate', datafield: 'vatRate', width: 120},
    { text: 'Queue Name', datafield: 'queueName', width: 120},
    { text: 'LongBot.Name', datafield: 'longbotName', width: 120},
    { text: 'Common Name', datafield: 'commonName', width: 120},
    { text: 'LongLabel Description', datafield: 'description', width: 120},
    { text: 'Picture File', datafield: 'file', width: 120},
]
export const LocationColumns = [
    { text: 'Location', datafield: 'location', width: 120},
    { text: 'User Batch', datafield: 'userBatch', width: 120},
    { text: 'Stock', datafield: 'stock', width: 120},
    { text: 'Alloc', datafield: 'alloc', width: 120},
    { text: 'To Come', datafield: 'toCome', width: 120},
    { text: 'Growing', datafield: 'growing', width: 120},
    { text: 'Week', datafield: 'week', width: 120},
    { text: 'Saleable', datafield: 'saleable', width: 120},
    { text: 'Initial Cost', datafield: 'initialCost', width: 120},
    { text: 'Own Stock', datafield: 'ownStock', width: 120},
    { text: 'Supplier', datafield: 'supplier', width: 120},
    { text: 'Pono', datafield: 'pono', width: 120},
    { text: 'Last Update', datafield: 'lastUpdate', width: 120},
    { text: 'User', datafield: 'user', width: 120},
    { text: 'Alloc.Grow', datafield: 'allocGrow', width: 120},
    { text: 'Batch', datafield: 'batch', width: 120},
    { text: 'GM user Field1', datafield: 'gmUserField1', width: 120},
    { text: 'GM user Field2', datafield: 'gmUserField2', width: 120},
    { text: 'Site', datafield: 'site', width: 120},
    { text: 'Passported', datafield: 'passported', width: 120},
    { text: 'Key', datafield: 'key', width: 120},
    { text: 'Location EAN13', datafield: 'locationEAN13', width: 120},
    { text: 'Unalloc', datafield: 'unalloc', width: 120},
    { text: 'Unalloc.Grow', datafield: 'unallocGrow', width: 120},
    { text: 'Prop.Date', datafield: 'propDate', width: 120},
    { text: 'Pot Date', datafield: 'potDate', width: 120},
    { text: 'Created', datafield: 'created', width: 120},
    { text: 'Stock Inc.Grow', datafield: 'stockInGrow', width: 120},
    { text: 'Tx Initial Cost', datafield: 'txInitialCost', width: 120},
    { text: 'ItemID', datafield: 'itemId', width: 120},
    { text: 'ProductID', datafield: 'productId', width: 120},
    { text: 'Initial Girth', datafield: 'initialGirth', width: 120},
    { text: 'Current Girth', datafield: 'currentGirth', width: 120},
    { text: 'Priority', datafield: 'priority', width: 120},
    { text: 'Batch Price', datafield: 'batchPrice', width: 120},
    { text: 'Tx Batch Price', datafield: 'txBatchPrice', width: 120},
    { text: 'Current Cost', datafield: 'currentCost', width: 120},
    { text: 'Tx Current Cost', datafield: 'txCurrentCost', width: 120},
    { text: 'National Register Ref', datafield: 'nationalRegisterRef', width: 120},
    { text: 'Master Certificate No', datafield: 'masterCetificateNo', width: 120},
    { text: 'Provenance', datafield: 'provenance', width: 120},
    { text: 'Origin', datafield: 'origin', width: 120},
    { text: 'Age', datafield: 'age', width: 120},
    { text: 'Cat.of Basic Material', datafield: 'cbm', width: 120},
    { text: 'Type of Basic Material', datafield: 'tbm', width: 120},
    { text: 'PerTray', datafield: 'perTray', width: 120},
    { text: 'On Transfer', datafield: 'onTransfer', width: 120},
    { text: 'STN No', datafield: 'STN', width: 120},
    { text: 'Booked In Date', datafield: 'bookedDate', width: 120},
    { text: 'Notes', datafield: 'notes', width: 120},
    { text: 'Supplier EAN13', datafield: 'supplierEAN13', width: 120},
    
];
export const CollectionColumns = [
    { text: 'Quantity', datafield: 'quantity', width: 120},
    { text: 'Key', datafield: 'key', width: 120},
    { text: 'Name', datafield: 'name', width: 120},
    { text: 'Size', datafield: 'size', width: 120},
    { text: 'Form', datafield: 'form', width: 120},
    { text: 'Start', datafield: 'start', width: 120},
    { text: 'Stock', datafield: 'stock', width: 120},
    { text: 'Order', datafield: 'order', width: 120},
    { text: 'To Come', datafield: 'toCome', width: 120},
    { text: 'Free', datafield: 'free', width: 120},
    { text: 'Alloc', datafield: 'alloc', width: 120},
    { text: 'Growing', datafield: 'growing', width: 120},
    { text: 'Sold', datafield: 'sold', width: 120},
    { text: 'Lost', datafield: 'lost', width: 120},
    { text: 'Warn', datafield: 'warn', width: 120},
    { text: 'Warn%', datafield: 'warnP', width: 120},
    { text: 'Alloc.Grow', datafield: 'allocGrow', width: 120},
    { text: 'Category', datafield: 'category', width: 120},
    { text: 'Sec.Size', datafield: 'secSize', width: 120},
    { text: 'Sec.Form', datafield: 'secForm', width: 120},
    { text: 'Price A1', datafield: 'priceA1', width: 120},
    { text: 'Price A2', datafield: 'priceA2', width: 120},
    { text: 'Price A3', datafield: 'priceA3', width: 120},
    { text: 'Price A4', datafield: 'priceA4', width: 120},
    { text: 'Price B1', datafield: 'priceB1', width: 120},
    { text: 'Price B2', datafield: 'priceB2', width: 120},
    { text: 'Price B3', datafield: 'priceB3', width: 120},
    { text: 'Price B4', datafield: 'priceB4', width: 120},
    { text: 'Passported', datafield: 'passported', width: 120},
    { text: 'EAN13', datafield: 'ean13', width: 120},
    { text: 'Name', datafield: 'nameP', width: 120},
    { text: 'Size', datafield: 'sizeP', width: 120},
    { text: 'Form', datafield: 'formP', width: 120},
    { text: 'Unused', datafield: 'unused', width: 120},
    { text: 'FreeInc.Grow', datafield: 'freeIncGrow', width: 120},
    { text: 'Unalloc', datafield: 'unalloc', width: 120},
    { text: 'Unalloc.Grow', datafield: 'unallocGrow', width: 120},
    { text: 'RetailA', datafield: 'retailA', width: 120},
    { text: 'RetailB', datafield: 'retailB', width: 120},
    { text: 'Item ID', datafield: 'itemId', width: 120},
];
// stock updated
export const StockColumns = [
    { text: 'Key', datafield: 'key', width: 120},
    { text: 'Name', datafield: 'name', width: 120},
    { text: 'Size', datafield: 'size', width: 120},
    { text: 'Form', datafield: 'form', width: 120},
    { text: 'Location', datafield: 'location', width: 120},
    { text: 'User Batch', datafield: 'userBatch', width: 120},
    { text: 'Stock', datafield: 'stock', width: 120},
    { text: 'Alloc', datafield: 'alloc', width: 120},
    { text: 'To Come', datafield: 'toCome', width: 120},
    { text: 'Available', datafield: 'available', width: 120},
    { text: 'On order', datafield: 'onOrder', width: 120},
    { text: 'Growing', datafield: 'growing', width: 120},
    { text: 'Alloc.Grow', datafield: 'allocGrow', width: 120},
    { text: 'Week', datafield: 'week', width: 120},
    { text: 'Saleable', datafield: 'saleable', width: 120},
    { text: 'Category', datafield: 'category', width: 120},
    { text: 'Class', datafield: 'class', width: 120},
    { text: 'Initial Cost', datafield: 'initialCost', width: 120},
    { text: 'Own', datafield: 'own', width: 120},
    { text: 'Supplier', datafield: 'supplier', width: 120},
    { text: 'Pono', datafield: 'pono', width: 120},
    { text: 'Last Update', datafield: 'lastUpdate', width: 120},
    { text: 'User', datafield: 'user', width: 120},
    { text: 'Key', datafield: 'userKey', width: 120},
    { text: 'Sec.Size', datafield: 'secSize', width: 120},
    { text: 'Sec.Form', datafield: 'secForm', width: 120},
    { text: 'GM user Field1', datafield: 'gmUserField1', width: 120},
    { text: 'GM user Field2', datafield: 'gmUserField2', width: 120},
    { text: 'Site', datafield: 'site', width: 120},
    { text: 'System Batch', datafield: 'systemBatch', width: 120},
    { text: 'Unalloc', datafield: 'unalloc', width: 120},
    { text: 'Unalloc.Grow', datafield: 'unallocGrow', width: 120},
    { text: 'Prop.Date', datafield: 'propDate', width: 120},
    { text: 'Pot Date', datafield: 'potDate', width: 120},
    { text: 'Unused', datafield: 'unused', width: 120},
    { text: 'Created', datafield: 'created', width: 120},
    { text: 'Unused', datafield: 'unusedP', width: 120},
    { text: 'Start', datafield: 'start', width: 120},
    { text: 'ItemID', datafield: 'itemId', width: 120},
    { text: 'ProductID', datafield: 'productId', width: 120},
    { text: 'Current Cost', datafield: 'currentCost', width: 120},
    { text: 'Initial Girth', datafield: 'initialGirth', width: 120},
    { text: 'Current Girth', datafield: 'currentGirth', width: 120},
    { text: 'Priority', datafield: 'priority', width: 120},
    { text: 'Master Certificate No', datafield: 'masterCetificateNo', width: 120},
    { text: 'Cert.Type', datafield: 'certType', width: 120},
    { text: 'Cert.Category', datafield: 'certCategory', width: 120},
    { text: 'Provenance', datafield: 'provenance', width: 120},
    { text: 'Seed Origin', datafield: 'seedOrigin', width: 120},
    { text: 'National Register Ref.', datafield: 'nationalRegisterRef', width: 120},
    { text: 'Veg.Prop', datafield: 'vegProp', width: 120},
    { text: 'Nature', datafield: 'nature', width: 120},
    { text: 'Passported', datafield: 'passported', width: 120},
    { text: 'Passport', datafield: 'passport', width: 120},
    { text: 'Replacement Passport', datafield: 'replacementPassport', width: 120},
    { text: 'Protected', datafield: 'protected', width: 120},
    { text: 'Protected Zones', datafield: 'protectedZone', width: 120},
    { text: 'Batch Price', datafield: 'batchPrice', width: 120},
    { text: 'Cert.Age', datafield: 'certAge', width: 120},
    { text: 'Tx Current Cost', datafield: 'txCurrentCost', width: 120},
    { text: 'Tx Batch Price', datafield: 'txBatchPrice', width: 120},
    { text: 'PerTray', datafield: 'perTray', width: 120},
    { text: 'On Transfer', datafield: 'onTransfer', width: 120},
    { text: 'STN No', datafield: 'STN', width: 120},
    { text: 'Booked In Date', datafield: 'bookedDate', width: 120},
    { text: 'Notes', datafield: 'notes', width: 120},
    { text: 'Supplier EAN13', datafield: 'supplierEAN13', width: 120},
    { text: 'Location EAN13', datafield: 'locationEAN13', width: 120},
];
export const StockUpdateDetailColumns = [
    { text: 'Date/Time', datafield: 'date', width: 120},
    { text: 'User', datafield: 'user', width: 120},
    { text: 'Reason', datafield: 'reason', width: 120},
    { text: 'Orig Loc', datafield: 'origLoc', width: 120},
    { text: 'New Loc', datafield: 'newLoc', width: 120},
    { text: 'Stock Change', datafield: 'stockChange', width: 120},
    { text: 'G Stock Change', datafield: 'gStockChange', width: 120},
    { text: 'Purch Change', datafield: 'purchChange', width: 120},
    { text: 'Alloc Change', datafield: 'allocChange', width: 120},
    { text: 'G Alloc Change', datafield: 'gAllocChange', width: 120},
    { text: 'Orig Stock', datafield: 'origStock', width: 120},
    { text: 'New Stock', datafield: 'newStock', width: 120},
    { text: 'Orig GStock', datafield: 'origGstock', width: 120},
    { text: 'New GStock', datafield: 'newGstock', width: 120},
    { text: 'Orig Initial Cost', datafield: 'origInitialCost', width: 120},
    { text: 'New Initial Cost', datafield: 'newInitialCost', width: 120},
    { text: 'Orig Alloc', datafield: 'origAlloc', width: 120},
    { text: 'New Alloc', datafield: 'newAlloc', width: 120},
    { text: 'Orig Grow Alloc', datafield: 'origGrowAlloc', width: 120},
    { text: 'New Grow Alloc', datafield: 'newGrowAlloc', width: 120},
    { text: 'Orig Class', datafield: 'origClass', width: 120},
    { text: 'New Class', datafield: 'newClass', width: 120},
    { text: 'Orig Batch', datafield: 'origBatch', width: 120},
    { text: 'New Batch', datafield: 'newBatch', width: 120},
    { text: 'Orig Sys Batch', datafield: 'origSysBatch', width: 120},
    { text: 'New Sys Batch', datafield: 'newSysBatch', width: 120},
    { text: 'Orig Purch', datafield: 'origPurch', width: 120},
    { text: 'New Purch', datafield: 'newPurch', width: 120},
    { text: 'Orig Transfer', datafield: 'origTransfer', width: 120},
    { text: 'New Transfer', datafield: 'newTransfer', width: 120},
    { text: 'Transfer Chang', datafield: 'transferChange', width: 120},
    { text: 'Orig Current Cost', datafield: 'origCost', width: 120},
    { text: 'New Current Cost', datafield: 'newCost', width: 120},
]
